### ISSUE TITLE
Create data site participation dashboard

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/participation-dashboard#23]
Coming back to the idea of having our first dashboard rendered with different (sub)set of data. At this point I'm looking for two rendering of the dashboard:

- Overall participation dashboard fed with all the data currently being used (done)
- For each data site, the same participation dashboard but when fed with only data for this data site.

The best way to select the data to use is probably at the level of the submission queues. As a reminder, for each NLP Sandbox task, we have an entrypoint, public-facing submission queue. We then have an internal queue for each data site that supports this task (not all data sites support all the tasks). Taking the example of the Date Annotation Task:

- Entrypoint queue ID: 9614652
- Sage internal queue ID: Sage is actually an exception and tap into the Entrypoint queue. :)
- MCW internal queue ID: 9614719

## Overall participation dashboard

Below are all the entrypoint queue IDs that can be used for the overall participation dashboard:

- Date annotation: 9614652
- Person name annotation: 9614657
- Contact annotation: 9614799
- ID annotation: 9614797
- Location annotation: 9614658

> Note: The current overall dashboard taken as input all the queues and report 6 tasks open. However the sixth task, covid-19 annotation, is not open yet. Filtering using submission queue will solve this issue.

How to identify the ID of the submissions (rows) to keep in the table `Main Admin View` from which participation data are obtained:

- Keep all the rows in `Main Admin View` (syn22277124) where `evaluationid` takes a value in the set of queue IDs listed above.

## MCW participation dashboard

MCW internal queue ID:

- Date annotation: 9614719
- Person name annotation: 9614720
- Contact annotation: 9614804
- ID annotation: 9614803
- Location annotation: 9614721

How to identify the ID of the submissions (rows) to keep in the table `Main Admin View` from which participation data are obtained:

1. Select all the rows in the table `MCW` (syn22277124) where `evaluationid` takes a value in the set of queue IDs listed above. From these rows, create a set of unique submission ID from the column `name` called `A`.
2. In the `Main Admin View` (syn22277124), keep all the rows where `id` takes a value in `A`.

## Participation dashboard template

The title of the dashboards rendered should be:

- NLP Sandbox
- NLP Sandbox - {data site name}
  - NLP Sandbox - MCW
  - NLP Sandbox - Sage Bionetworks (in the future, for now it's not convenient because of the Sage Bionetworks data site is not like the other data site, see note above)

## Configuration

Consider adding a (JSON) configuration file to the code base to customize the rendering of the participation dashboard, and soon other dashboards. At this point, for the participation dashboard, the configuration file should define the submission queue to use to filter the data and the title of the dashboard.

**Comment by andrewelamb** [comment]
@tschaffter some questions:

Is a datasite an organization that is providing us the training/testing data?

What is MCW? 

Wjats the difference between the MCW queue and the Main Admin View?
