### ISSUE TITLE
New dashboard - Report the evolution of the performance of all the submission for a given task

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/participation-dashboard#25]
## Goal

For each task, draw a plot similar to [this one from paperswithcode](https://paperswithcode.com/sota/semantic-segmentation-on-cityscapes). In this plot, the performance of each submissions is represented by a dot.

- X axis: time (range: determine by the timestamp of the submissions)
- Y axis: performance (range: min score to max score)

The blue line represents the evolution of the best submission.

It would be great to include this plot on the top of the leaderboard page of each task. Therefore, individual HTML file should be rendered for each task.

**Comment by andrewelamb** [comment]
![Screenshot from 2021-08-31 08-35-19](https://user-images.githubusercontent.com/7220713/131532893-ee6d9bb7-7b27-4d1a-ba7c-410af24f4819.png)
