### ISSUE TITLE
Use different icons for the tiles in the participation dashboard

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/participation-dashboard#33]
Flexdashboard icons; https://rstudio.github.io/flexdashboard/articles/using.html#icon-sets

**Comment by andrewelamb** [comment]
@tschaffter Do you have any in mind, or should I use my best judgement? :)

**Comment by andrewelamb** [comment]
![Screenshot from 2021-09-02 07-37-45](https://user-images.githubusercontent.com/7220713/131864352-5302c12f-d5db-4ae5-8604-a6c010182973.png)

**Comment by tschaffter** [comment]
- Task:
  - https://fontawesome.com/v5.15/icons/tasks?style=solid
- Schema
  - https://fontawesome.com/v5.15/icons/project-diagram?style=solid
- Data site:
  - https://fontawesome.com/v5.15/icons/hospital?style=solid
- Tools
  - https://fontawesome.com/v5.15/icons/cog?style=solid

**Comment by tschaffter** [comment]
@andrewelamb Can you place the gauge tile in the available slot above the second bar plot?

**Comment by tschaffter** [comment]
Thinking also to update the layout to give bar plot more space along the x-axis.

Example:

![image](https://user-images.githubusercontent.com/3056480/132263192-e492b6bf-34b7-434d-b482-30ad768f623d.png)

**Comment by andrewelamb** [comment]
@tschaffter 

If we went to a column layout, would you want both plots in the larger column, and the gauge in the smaller column with the value boxes?

**Comment by andrewelamb** [comment]
![Screenshot from 2021-09-07 09-06-52](https://user-images.githubusercontent.com/7220713/132376771-a6e0a066-3848-43a1-b3d6-f306c4471dea.png)

**Comment by andrewelamb** [comment]
![Screenshot from 2021-09-07 11-57-43](https://user-images.githubusercontent.com/7220713/132396927-2c699679-714e-4aea-9ce7-74781794f974.png)

**Comment by tschaffter** [comment]
@andrewelamb Looks good!
